name: tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test-job:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - shell: bash
        run: ifconfig
          
